### ISSUE TITLE
tag version 2.1.0

### ISSUE THREAD

**Issue by agebhar1** [zendesk/ember-resource#104]
@shajith thanks for release 2.1.0 (https://github.com/zendesk/ember-resource/commit/330b3f3300d119a3d7ae4535d0e54843e515832e)

To make use of [semver](http://semver.org/) please create a tag for v2.1.0 -- thanks in advance

**Comment by shajith** [comment]
@agebhar1: oops, missed that, thanks for the heads-up. Tagged v2.1.0 now.

**Comment by agebhar1** [comment]
@shajith that's life :smirk: 
work's & thanks
